services:
   wp_mysql:
     image: mysql:8
     container_name: wp_mysql
     ports:
       - "3336:3306"
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wpdb
       MYSQL_USER: wpuser
       MYSQL_PASSWORD: wppass
   wp:
     depends_on:
       - wp_mysql
     image: wordpress:latest
     container_name: wp
     volumes:
       - ./wp-content:/var/www/html/wp-content
     ports:
       - "8888:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: wp_mysql
       WORDPRESS_DB_NAME: wpdb
       WORDPRESS_DB_USER: wpuser
       WORDPRESS_DB_PASSWORD: wppass
       WORDPRESS_DEBUG: 1
volumes:
    db_data:
